name: 'Index Markdown Pages'
author: 'Yuki Takagi'
description: 'Collect the markdown files in the repository and create an index'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  root-patterns:
    description: 'Glob patterns (separated by newlines) matching the root documents. The indexes will be written to that documents.'
    required: false
    default: 'README.md'
  exclude-patterns:
    description: 'Glob patterns (separated by newlines) matching the documents to be excluded from the index.'
    required: false
    default: ''
  header:
    description: 'Header to be added to the index.'
    required: false
    default: '## Index'
runs:
  using: 'node20'
  main: 'dist/index.js'
