name: 'Index Markdown Pages'
author: 'Yuki Takagi'
description: 'Collect the markdown files in the repository and create an index'
inputs:
  root-patterns:
    description: 'Glob patterns (separated by newlines) matching the root documents. The indexes will be written to that documents.'
    required: false
    default: 'README.md'
  header:
    description: 'Header to be added to the index'
    required: false
    default: '## Index'
runs:
  using: 'node20'
  main: 'dist/index.js'
