name: example
on:
  push:
    branches:
      - main
jobs:
  test:
    name: "Example"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: ./
        with:
          root-patterns: "example/README.md"
          exclude-patterns: "example/exclude/**/*"
          header: "## Index"
      - run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git add .
            git commit -m "docs: Update index"
            git push
          fi
